#############################################################################
# Makefile for building: QCDBEdit.app/Contents/MacOS/QCDBEdit
# Generated by qmake (2.01a) (Qt 4.5.1) on: Thu Jul 4 14:21:54 2013
# Project:  QCDBEdit.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile QCDBEdit.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_KEYWORDS -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.5/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/usr/include/QtXml -I/Library/Frameworks/QtSql.framework/Versions/4/Headers -I/usr/include/QtSql -I/usr/include -I/usr/local/include -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework OpenGL -framework AGL -framework QtSql -framework QtXml -framework QtGui -framework Carbon -framework AppKit -framework QtCore -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = main.C \
		QCDBEditApplication.C \
		QMsgBox.C \
		MainWindow.C \
		OptionDatabase.C \
		Option.C \
		EditOptionDialog.C \
		OptionListEditor.C \
		OptionNumberEditor.C moc_QCDBEditApplication.cpp \
		moc_QMsgBox.cpp \
		moc_MainWindow.cpp \
		moc_EditOptionDialog.cpp \
		moc_OptionListEditor.cpp \
		moc_OptionNumberEditor.cpp \
		qrc_QCDBEdit.cpp
OBJECTS       = build/main.o \
		build/QCDBEditApplication.o \
		build/QMsgBox.o \
		build/MainWindow.o \
		build/OptionDatabase.o \
		build/Option.o \
		build/EditOptionDialog.o \
		build/OptionListEditor.o \
		build/OptionNumberEditor.o \
		build/moc_QCDBEditApplication.o \
		build/moc_QMsgBox.o \
		build/moc_MainWindow.o \
		build/moc_EditOptionDialog.o \
		build/moc_OptionListEditor.o \
		build/moc_OptionNumberEditor.o \
		build/qrc_QCDBEdit.o
DIST          = /usr/local/Qt4.5/mkspecs/common/unix.conf \
		/usr/local/Qt4.5/mkspecs/common/mac.conf \
		/usr/local/Qt4.5/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.5/mkspecs/qconfig.pri \
		/usr/local/Qt4.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.5/mkspecs/features/debug.prf \
		/usr/local/Qt4.5/mkspecs/features/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt4.5/mkspecs/features/qt.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.5/mkspecs/features/moc.prf \
		/usr/local/Qt4.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.5/mkspecs/features/resources.prf \
		/usr/local/Qt4.5/mkspecs/features/uic.prf \
		/usr/local/Qt4.5/mkspecs/features/yacc.prf \
		/usr/local/Qt4.5/mkspecs/features/lex.prf \
		/usr/local/Qt4.5/mkspecs/features/include_source_dir.prf \
		QCDBEdit.pro
QMAKE_TARGET  = QCDBEdit
DESTDIR       = 
TARGET        = QCDBEdit.app/Contents/MacOS/QCDBEdit

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile QCDBEdit.app/Contents/PkgInfo QCDBEdit.app/Contents/Resources/empty.lproj QCDBEdit.app/Contents/Info.plist QCDBEdit.app/Contents/Resources/QCDBEdit.icns $(TARGET)

$(TARGET): ui_MainWindow.h ui_EditOptionDialog.h ui_OptionListEditor.h ui_OptionNumberEditor.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) QCDBEdit.app/Contents/MacOS/ || $(MKDIR) QCDBEdit.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QCDBEdit.pro  /usr/local/Qt4.5/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.5/mkspecs/common/unix.conf \
		/usr/local/Qt4.5/mkspecs/common/mac.conf \
		/usr/local/Qt4.5/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.5/mkspecs/qconfig.pri \
		/usr/local/Qt4.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.5/mkspecs/features/debug.prf \
		/usr/local/Qt4.5/mkspecs/features/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt4.5/mkspecs/features/qt.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.5/mkspecs/features/moc.prf \
		/usr/local/Qt4.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.5/mkspecs/features/resources.prf \
		/usr/local/Qt4.5/mkspecs/features/uic.prf \
		/usr/local/Qt4.5/mkspecs/features/yacc.prf \
		/usr/local/Qt4.5/mkspecs/features/lex.prf \
		/usr/local/Qt4.5/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtSql.framework/QtSql.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtXml.framework/QtXml.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl
	$(QMAKE) -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile QCDBEdit.pro
/usr/local/Qt4.5/mkspecs/common/unix.conf:
/usr/local/Qt4.5/mkspecs/common/mac.conf:
/usr/local/Qt4.5/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.5/mkspecs/qconfig.pri:
/usr/local/Qt4.5/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.5/mkspecs/features/qt_config.prf:
/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.5/mkspecs/features/default_pre.prf:
/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.5/mkspecs/features/debug.prf:
/usr/local/Qt4.5/mkspecs/features/default_post.prf:
/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.5/mkspecs/features/unix/opengl.prf:
/usr/local/Qt4.5/mkspecs/features/qt.prf:
/usr/local/Qt4.5/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.5/mkspecs/features/moc.prf:
/usr/local/Qt4.5/mkspecs/features/warn_on.prf:
/usr/local/Qt4.5/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.5/mkspecs/features/resources.prf:
/usr/local/Qt4.5/mkspecs/features/uic.prf:
/usr/local/Qt4.5/mkspecs/features/yacc.prf:
/usr/local/Qt4.5/mkspecs/features/lex.prf:
/usr/local/Qt4.5/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtSql.framework/QtSql.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtXml.framework/QtXml.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile QCDBEdit.pro

QCDBEdit.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) QCDBEdit.app/Contents || $(MKDIR) QCDBEdit.app/Contents 
	@$(DEL_FILE) QCDBEdit.app/Contents/PkgInfo
	@echo "APPL????" >QCDBEdit.app/Contents/PkgInfo
QCDBEdit.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) QCDBEdit.app/Contents/Resources || $(MKDIR) QCDBEdit.app/Contents/Resources 
	@touch QCDBEdit.app/Contents/Resources/empty.lproj
	
QCDBEdit.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) QCDBEdit.app/Contents || $(MKDIR) QCDBEdit.app/Contents 
	@$(DEL_FILE) QCDBEdit.app/Contents/Info.plist
	@sed -e "s,@ICON@,QCDBEdit.icns,g" -e "s,@EXECUTABLE@,QCDBEdit,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.5/mkspecs/macx-g++/Info.plist.app >QCDBEdit.app/Contents/Info.plist
QCDBEdit.app/Contents/Resources/QCDBEdit.icns: resources/QCDBEdit.icns
	@$(CHK_DIR_EXISTS) QCDBEdit.app/Contents/Resources/ || $(MKDIR) QCDBEdit.app/Contents/Resources/ 
	@$(DEL_FILE) QCDBEdit.app/Contents/Resources/QCDBEdit.icns
	@$(COPY_FILE) resources/QCDBEdit.icns QCDBEdit.app/Contents/Resources/QCDBEdit.icns
dist: 
	@$(CHK_DIR_EXISTS) build/QCDBEdit1.0.0 || $(MKDIR) build/QCDBEdit1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/QCDBEdit1.0.0/ && $(COPY_FILE) --parents QCDBEditApplication.h QMsgBox.h MainWindow.h OptionDatabase.h Option.h EditOptionDialog.h OptionListEditor.h OptionNumberEditor.h build/QCDBEdit1.0.0/ && $(COPY_FILE) --parents QCDBEdit.qrc build/QCDBEdit1.0.0/ && $(COPY_FILE) --parents main.C QCDBEditApplication.C QMsgBox.C MainWindow.C OptionDatabase.C Option.C EditOptionDialog.C OptionListEditor.C OptionNumberEditor.C build/QCDBEdit1.0.0/ && $(COPY_FILE) --parents MainWindow.ui EditOptionDialog.ui OptionListEditor.ui OptionNumberEditor.ui build/QCDBEdit1.0.0/ && (cd `dirname build/QCDBEdit1.0.0` && $(TAR) QCDBEdit1.0.0.tar QCDBEdit1.0.0 && $(COMPRESS) QCDBEdit1.0.0.tar) && $(MOVE) `dirname build/QCDBEdit1.0.0`/QCDBEdit1.0.0.tar.gz . && $(DEL_FILE) -r build/QCDBEdit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r QCDBEdit.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_QCDBEditApplication.cpp moc_QMsgBox.cpp moc_MainWindow.cpp moc_EditOptionDialog.cpp moc_OptionListEditor.cpp moc_OptionNumberEditor.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_QCDBEditApplication.cpp moc_QMsgBox.cpp moc_MainWindow.cpp moc_EditOptionDialog.cpp moc_OptionListEditor.cpp moc_OptionNumberEditor.cpp
moc_QCDBEditApplication.cpp: QCDBEditApplication.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ QCDBEditApplication.h -o moc_QCDBEditApplication.cpp

moc_QMsgBox.cpp: QMsgBox.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ QMsgBox.h -o moc_QMsgBox.cpp

moc_MainWindow.cpp: ui_MainWindow.h \
		MainWindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ MainWindow.h -o moc_MainWindow.cpp

moc_EditOptionDialog.cpp: ui_EditOptionDialog.h \
		EditOptionDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ EditOptionDialog.h -o moc_EditOptionDialog.cpp

moc_OptionListEditor.cpp: ui_OptionListEditor.h \
		OptionListEditor.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ OptionListEditor.h -o moc_OptionListEditor.cpp

moc_OptionNumberEditor.cpp: ui_OptionNumberEditor.h \
		OptionNumberEditor.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ OptionNumberEditor.h -o moc_OptionNumberEditor.cpp

compiler_rcc_make_all: qrc_QCDBEdit.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_QCDBEdit.cpp
qrc_QCDBEdit.cpp: QCDBEdit.qrc \
		resources/qmsgbox/question.png \
		resources/qmsgbox/information.png \
		resources/qmsgbox/critical.png \
		resources/qmsgbox/warning.png \
		resources/QCDBEdit.png \
		resources/QCDBEdit.icns \
		resources/icons/Up.png \
		resources/icons/Add.png \
		resources/icons/Down.png \
		resources/icons/Delete.png
	/Developer/Tools/Qt/rcc -name QCDBEdit QCDBEdit.qrc -o qrc_QCDBEdit.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_MainWindow.h ui_EditOptionDialog.h ui_OptionListEditor.h ui_OptionNumberEditor.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainWindow.h ui_EditOptionDialog.h ui_OptionListEditor.h ui_OptionNumberEditor.h
ui_MainWindow.h: MainWindow.ui
	/Developer/Tools/Qt/uic MainWindow.ui -o ui_MainWindow.h

ui_EditOptionDialog.h: EditOptionDialog.ui
	/Developer/Tools/Qt/uic EditOptionDialog.ui -o ui_EditOptionDialog.h

ui_OptionListEditor.h: OptionListEditor.ui
	/Developer/Tools/Qt/uic OptionListEditor.ui -o ui_OptionListEditor.h

ui_OptionNumberEditor.h: OptionNumberEditor.ui
	/Developer/Tools/Qt/uic OptionNumberEditor.ui -o ui_OptionNumberEditor.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/main.o: main.C QCDBEditApplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.C

build/QCDBEditApplication.o: QCDBEditApplication.C QCDBEditApplication.h \
		QMsgBox.h \
		MainWindow.h \
		ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QCDBEditApplication.o QCDBEditApplication.C

build/QMsgBox.o: QMsgBox.C QMsgBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QMsgBox.o QMsgBox.C

build/MainWindow.o: MainWindow.C MainWindow.h \
		ui_MainWindow.h \
		OptionDatabase.h \
		EditOptionDialog.h \
		ui_EditOptionDialog.h \
		QMsgBox.h \
		Option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainWindow.o MainWindow.C

build/OptionDatabase.o: OptionDatabase.C OptionDatabase.h \
		QMsgBox.h \
		Option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/OptionDatabase.o OptionDatabase.C

build/Option.o: Option.C Option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Option.o Option.C

build/EditOptionDialog.o: EditOptionDialog.C EditOptionDialog.h \
		ui_EditOptionDialog.h \
		OptionNumberEditor.h \
		ui_OptionNumberEditor.h \
		OptionListEditor.h \
		ui_OptionListEditor.h \
		Option.h \
		QMsgBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/EditOptionDialog.o EditOptionDialog.C

build/OptionListEditor.o: OptionListEditor.C OptionListEditor.h \
		ui_OptionListEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/OptionListEditor.o OptionListEditor.C

build/OptionNumberEditor.o: OptionNumberEditor.C OptionNumberEditor.h \
		ui_OptionNumberEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/OptionNumberEditor.o OptionNumberEditor.C

build/moc_QCDBEditApplication.o: moc_QCDBEditApplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_QCDBEditApplication.o moc_QCDBEditApplication.cpp

build/moc_QMsgBox.o: moc_QMsgBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_QMsgBox.o moc_QMsgBox.cpp

build/moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MainWindow.o moc_MainWindow.cpp

build/moc_EditOptionDialog.o: moc_EditOptionDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_EditOptionDialog.o moc_EditOptionDialog.cpp

build/moc_OptionListEditor.o: moc_OptionListEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_OptionListEditor.o moc_OptionListEditor.cpp

build/moc_OptionNumberEditor.o: moc_OptionNumberEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_OptionNumberEditor.o moc_OptionNumberEditor.cpp

build/qrc_QCDBEdit.o: qrc_QCDBEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_QCDBEdit.o qrc_QCDBEdit.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

